{% set version = "2.4.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-namedropr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/namedropR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/namedropR/namedropR_{{ version }}.tar.gz
  sha256: eaff9d1d9896beaa16e293ff24beb16a7de8a573ae6b2a4db51dc51a031a8f1a

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r.utils
    - r-bib2df
    - r-dplyr
    - r-htmltools
    - r-lubridate
    - r-qrcode
    - r-readr
    - r-stringr
    - r-webshot
  run:
    - r-base
    - r-r.utils
    - r-bib2df
    - r-dplyr
    - r-htmltools
    - r-lubridate
    - r-qrcode
    - r-readr
    - r-stringr
    - r-webshot

test:
  commands:
    - $R -e "library('namedropR')"           # [not win]
    - "\"%R%\" -e \"library('namedropR')\""  # [win]

about:
  home: https://github.com/nucleic-acid/namedropR
  license: MIT
  summary: Provides 'visual citations' containing the metadata of a scientific paper and a 'QR' code. A 'visual citation' is a banner containing title, authors, journal and year of a publication. This package can create such banners based on 'BibTeX' and 'BibLaTeX' references and includes a QR code pointing to the 'DOI'.
    The resulting HTML object or PNG image can be included in a presentation to point the audience to good resources for further reading. Styling is possible via predefined designs or via custom 'CSS'. This package is not intended as replacement for proper reference manager packages, but a tool to enrich scientific presentation
    slides.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
